import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import TopBar from '@/components/TopBar';
import Main from '@/components/Main';
import Footer from '@/components/Footer';

export default function Home() {
  return (
    <div className={styles.main}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/calcule-pra-mim-logo.png" />
        <script src="https://kit.fontawesome.com/c70750bce8.js" crossorigin="anonymous"></script>
      </Head>
      <TopBar></TopBar>
      <Main></Main>
      <Footer></Footer>
    </div>
  )
}
