import Head from 'next/head';
import TopBar from '@/components/TopBar';
import Main from '@/components/Main';
import Footer from '@/components/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/calcule-pra-mim-logo.png" />
        
      </Head>
      <TopBar></TopBar>
      <Main></Main>
      <Footer></Footer>
    </>
  )
}
